using System;
using NUnit.Framework;
using UnityEngine;
public class HonorsMarkerProfileTests {
    static ARMarkerProfileRegistry.Bundle Bundle()=>JsonUtility.FromJson<ARMarkerProfileRegistry.Bundle>(Resources.Load<TextAsset>("Honors/marker_profiles").text);
    [Test] public void LegacyEquivalentAndPendingHorizontal(){var b=Bundle();var p=b.profiles[0];Assert.IsTrue(p.Validate(out var e),e);var t=new HonorsMarkerTransform(p);var legacy=new ModelCoordinateTransform(1,ARStructure.MarkerOnColumn,true);foreach(var x in new[]{Vector3.zero,ARStructure.MarkerOnColumn,new Vector3(7,-3,12)}){Assert.Less((t.Forward(x)-legacy.Forward(x)).magnitude,1e-5);Assert.Less((t.Inverse(t.Forward(x))-x).magnitude,1e-5);}Assert.IsFalse(b.profiles[1].enabled);Assert.IsFalse(b.profiles[1].physicalVerified);}
    [Test] public void GeneralBasisInverseUsesTranspose(){var p=Bundle().profiles[0];var r=Matrix4x4.Rotate(Quaternion.Euler(20,30,40));p.mx=r.MultiplyVector(p.mx);p.my=r.MultiplyVector(p.my);p.mz=r.MultiplyVector(p.mz);p.scale=.01f;var t=new HonorsMarkerTransform(p);var x=new Vector3(7,5,3);Assert.Less((t.Inverse(t.Forward(x))-x).magnitude,1e-4);Assert.That(p.Basis.determinant,Is.EqualTo(-1).Within(1e-5));}
    [Test] public void InvalidProfilesIdentityAndModelRejected(){var b=Bundle();var p=b.profiles[0];p.scale=0;Assert.IsFalse(p.Validate(out _));p=Bundle().profiles[0];p.mx=p.my;Assert.IsFalse(p.Validate(out _));p=Bundle().profiles[0];p.reference.x=float.NaN;Assert.IsFalse(p.Validate(out _));b=Bundle();b.profiles[1].markerId=b.profiles[0].markerId;Assert.Throws<ArgumentException>(()=>new ARMarkerProfileRegistry(JsonUtility.ToJson(b),b.profiles[0].modelSHA256));b=Bundle();var reg=new ARMarkerProfileRegistry(JsonUtility.ToJson(b),b.profiles[0].modelSHA256);Assert.IsFalse(reg.TryGet("unknown","",out _));Assert.IsFalse(reg.TryGet(b.profiles[1].markerId,b.profiles[1].imageGuid,out _));Assert.Throws<ArgumentException>(()=>new ARMarkerProfileRegistry(JsonUtility.ToJson(b),new string('0',64)));}
    [Test] public void RelativeNormStatisticsDoNotCancel(){var s=ARRegistrationRecorder.Statistics(new[]{10f,10f,20f,40f});Assert.That(s.median,Is.EqualTo(15));Assert.That(s.max,Is.EqualTo(40));Assert.That(s.p95,Is.EqualTo(40));Assert.That(s.rms,Is.EqualTo(Mathf.Sqrt(550)).Within(1e-5));}
}
