using NUnit.Framework;
using UnityEngine;
public class StructuralDomainTests {
    StructuralRepository repo;
    [SetUp] public void Setup(){repo=new StructuralRepository(JsonUtility.FromJson<StructureData>(Resources.Load<TextAsset>("estructura_p1l4_unity").text));}
    [Test] public void RealDatasetAndWallMapping(){Assert.That(repo.Errors,Is.Empty);Assert.That(repo.Nodes.Count,Is.EqualTo(718));Assert.That(repo.Elements.Count,Is.EqualTo(1023));Assert.That(repo.Walls.Count,Is.EqualTo(91));Assert.That(repo.Walls[13].analyticalId,Is.EqualTo(618));Assert.That(repo.Cases.Count,Is.EqualTo(7));}
    [Test] public void MissingAndPartialAreNotZero(){Assert.IsFalse(repo.TryForces(-9,"C1",out _,out var missing));Assert.That(missing,Is.EqualTo(ResultAvailability.Missing));var data=JsonUtility.FromJson<StructureData>(Resources.Load<TextAsset>("estructura_p1l4_unity").text);data.p1l4.elementForces[0].f=new float[2];var partial=new StructuralRepository(data);var rec=data.p1l4.elementForces[0];Assert.IsFalse(partial.TryForces(rec.id,rec.combo,out _,out var state));Assert.That(state,Is.EqualTo(ResultAvailability.Partial));}
    [Test] public void TrueZeroIsAvailable(){var data=JsonUtility.FromJson<StructureData>(Resources.Load<TextAsset>("estructura_p1l4_unity").text);var r=data.p1l4.elementForces[0];r.f=new float[12];var zeros=new StructuralRepository(data);Assert.IsTrue(zeros.TryForces(r.id,r.combo,out var f,out var state));Assert.That(state,Is.EqualTo(ResultAvailability.Available));Assert.That(f[0],Is.EqualTo(0));}
    [Test] public void InvalidDuplicateAndFailedCase(){var d=JsonUtility.FromJson<StructureData>(Resources.Load<TextAsset>("estructura_p1l4_unity").text);d.nodes[1].id=d.nodes[0].id;Assert.IsFalse(new StructuralRepository(d).ContractValid);d=JsonUtility.FromJson<StructureData>(Resources.Load<TextAsset>("estructura_p1l4_unity").text);d.p1l4.caseStates[0].ok=false;var r=new StructuralRepository(d);Assert.IsFalse(r.TryForces(243,d.p1l4.caseStates[0].name,out _,out var a));Assert.That(a,Is.EqualTo(ResultAvailability.Invalid));}
    [TestCase(true,1f)] [TestCase(false,.01f)] [TestCase(false,.0021172f)]
    public void TransformRoundTripAndAnchorComposition(bool column,float scale){var t=new ModelCoordinateTransform(scale,column?ARStructure.MarkerOnColumn:new Vector3(-.7375f,-1.8683f,0),column);var p=new Vector3(3,-7.25f,7.92f);Assert.That((t.Inverse(t.Forward(p))-p).magnitude,Is.LessThan(1e-5));var anchor=new Pose(new Vector3(8,-2,5),Quaternion.Euler(17,29,6));Assert.That((t.FromWorld(t.World(p,anchor),anchor)-p).magnitude,Is.LessThan(.001f));float determinant=Vector3.Dot(t.Direction(Vector3.right),Vector3.Cross(t.Direction(Vector3.up),t.Direction(Vector3.forward)));Assert.That(determinant,Is.EqualTo(-1).Within(1e-6));}
    [Test] public void CalibratedColumnPoints(){var t=new ModelCoordinateTransform(1,ARStructure.MarkerOnColumn,true);Assert.That((t.Forward(repo.Point(23))-new Vector3(0,-.35f,-1.2f)).magnitude,Is.LessThan(1e-5));Assert.That((t.Forward(repo.Point(54))-new Vector3(0,-.35f,2.76f)).magnitude,Is.LessThan(1e-5));}
    [TestCase(1,0,0)] [TestCase(-1,0,0)] [TestCase(0,1,0)] [TestCase(0,-1,0)] [TestCase(0,0,1)] [TestCase(1,2,3)]
    public void UniformLoadAxesAndEnds(float x,float y,float z){var dir=new Vector3(x,y,z);StructuralResultSampler.Axes(dir,out var lx,out var ly,out var lz);Assert.That(Vector3.Dot(lx,ly),Is.EqualTo(0).Within(1e-5));Assert.That(Vector3.Cross(lx,ly),Is.EqualTo(lz));var f=new float[12];Assert.That(StructuralResultSampler.Evaluate(f,0,4,6,dir),Is.All.EqualTo(0));Assert.That(StructuralResultSampler.Evaluate(f,1,4,6,dir),Is.All.EqualTo(0));var mid=StructuralResultSampler.Evaluate(f,.5f,4,6,dir);var moment=-12*Vector3.Cross(lx,new Vector3(0,0,-1));Assert.That(mid[4],Is.EqualTo(Vector3.Dot(moment,ly)).Within(1e-5));Assert.That(mid[5],Is.EqualTo(Vector3.Dot(moment,lz)).Within(1e-5));}
    [Test] public void SixDiagramsExtremaAndFloatDisplay(){var sampler=new StructuralResultSampler(repo);var e=repo.Elements[72];for(int c=0;c<6;c++){Assert.IsTrue(sampler.TryDiagram(e,"C1",c,out var d,out _));Assert.That(d.Minimum,Is.LessThanOrEqualTo(d.Initial));Assert.That(d.Maximum,Is.GreaterThanOrEqualTo(d.Final));Assert.That(d.X[0],Is.EqualTo(0));Assert.That(d.X[d.X.Length-1],Is.EqualTo(7.51f).Within(1e-4));}Assert.IsTrue(sampler.TryAt(repo.Elements[243],"C1",0,out var cut,out _));Assert.That(cut[0],Is.EqualTo(-1679.79036f).Within(.001f));Assert.That(cut[3],Is.EqualTo(2.020908f).Within(.0001f));Assert.IsTrue(sampler.TryPM(repo.Elements[243],"C1",out var pm));Assert.That(pm.x,Is.EqualTo(1655.53536f).Within(.001f));}
    [Test] public void CapacityAssociationAndMissing(){Assert.IsNotNull(repo.Curve(repo.Elements[243].pmCurveId));Assert.IsNotNull(repo.Curve(repo.WallRegistry(13).pmSectionId));Assert.IsNull(repo.Curve("inexistente"));}
    [Test] public void LegacyMissingCannotBePhysicalZero(){UnityData.LoadData(repo.Data);Assert.IsTrue(float.IsNaN(UnityData.GetNodeDisplacement("C1",-999).x));Assert.IsTrue(float.IsNaN(UnityData.PMDemand(repo.Elements[243],"INVALID").x));Assert.IsTrue(UnityData.TryGetNodeDisplacement("C1",23,out _,out _));}
    [Test] public void CorruptAppliedLoadAndVisualMappingAreInvalid(){var load=repo.Data.p1l4.appliedLoads[0];load.values[0]=float.NaN;Assert.IsFalse(new StructuralRepository(repo.Data).ContractValid);}
    [Test] public void WallDemandsCoverAllExportedCases(){foreach(var w in repo.Data.p1l4.wallRegistry)Assert.That(w.demands.Length,Is.EqualTo(7));}
}
